version: '3'

services:
  iobroker:
    restart: always
    build: ./iobroker
    container_name: iobroker
    hostname: iobroker
    ports:
    - "8081:8081"
    volumes:
    - ./iobrokerdata:/opt/iobroker
    - ..:/workspace:cached