/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "google-spreadsheet adapter settings": {         "uk": "Налаштування адаптера для google-spreadsheet",    "en": "Adapter settings for google-spreadsheet",         "de": "Adaptereinstellungen für google-spreadsheet",     "ru": "Настройки адаптера для google-spreadsheet",       "pt": "Configurações do adaptador para google-spreadsheet", "nl": "Adapterinstellingen voor google-spreadsheet",     "fr": "Paramètres d'adaptateur pour google-spreadsheet", "it": "Impostazioni dell'adattatore per google-spreadsheet", "es": "Ajustes del adaptador para google-spreadsheet",   "pl": "Ustawienia adaptera dla google-spreadsheet",      "zh-cn": "google-spreadsheet的适配器设置"},
    "privateKey": {                                  "en": "private key",                                     "de": "Privater Schlüssel",                              "ru": "закрытый ключ",                                   "pt": "chave privada",                                   "nl": "prive sleutel",                                   "fr": "Clé privée",                                      "it": "chiave privata",                                  "es": "llave privada",                                   "pl": "prywatny klucz",                                  "zh-cn": "私钥"},
    "serviceAccountEmail": {                         "en": "service account",                                 "de": "E-Mail-Adresse des Dienstkontos",                 "ru": "электронная почта сервисного аккаунта",           "pt": "e-mail da conta de serviço",                      "nl": "e-mail van het serviceaccount",                   "fr": "e-mail du compte de service",                     "it": "e-mail dell'account di servizio",                 "es": "correo electrónico de la cuenta de servicio",     "pl": "adres e-mail konta usługi",                       "zh-cn": "服务帐户电子邮件"},
    "sheetName": {                                   "en": "sheet name",                                      "de": "Blattname",                                       "ru": "имя листа",                                       "pt": "nomedaplanilha",                                  "nl": "bladNaam",                                        "fr": "NomFeuille",                                      "it": "foglioNome",                                      "es": "hojaNombre",                                      "pl": "nazwa arkusza",                                   "zh-cn": "工作表名称"},
    "spreadsheetId": {                               "en": "spreadsheet id",                                  "de": "Tabellenkalkulations-ID",                         "ru": "идентификатор электронной таблицы",               "pt": "ID da planilha",                                  "nl": "spreadsheetId",                                   "fr": "ID de feuille de calcul",                         "it": "ID foglio di calcolo",                            "es": "ID de hoja de cálculo",                           "pl": "identyfikator arkusza kalkulacyjnego",            "zh-cn": "电子表格ID"},
};