/* eslint no-unused-vars: off */
/* eslint no-global-assign: off */
/* global systemDictionary */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
"use strict";

systemDictionary = {
    "google-spreadsheet adapter settings": {
        "en": "Adapter settings for google-spreadsheet",
        "de": "Adaptereinstellungen für google-spreadsheet",
        "ru": "Настройки адаптера для google-spreadsheet",
        "pt": "Configurações do adaptador para google-spreadsheet",
        "nl": "Adapterinstellingen voor google-spreadsheet",
        "fr": "Paramètres d'adaptateur pour google-spreadsheet",
        "it": "Impostazioni dell'adattatore per google-spreadsheet",
        "es": "Ajustes del adaptador para google-spreadsheet",
        "pl": "Ustawienia adaptera dla google-spreadsheet",
        "uk": "Налаштування адаптера для google-spreadsheet",
        "zh-cn": "google-spreadsheet的适配器设置"
    },
    "option1": {
        "en": "option1",
        "de": "Option 1",
        "ru": "Опция 1",
        "pt": "Opção 1",
        "nl": "Optie 1",
        "fr": "Option 1",
        "it": "opzione 1",
        "es": "Opción 1",
        "pl": "opcja 1",
        "uk": "варіант1",
        "zh-cn": "选项1"
    },
    "option2": {
        "en": "option2",
        "de": "Option 2",
        "ru": "вариант 2",
        "pt": "opção 2",
        "nl": "Optie 2",
        "fr": "Option 2",
        "it": "opzione 2",
        "es": "opcion 2",
        "pl": "Opcja 2",
        "uk": "варіант2",
        "zh-cn": "选项2"
    }
};